#!/usr/bin/env python
import argparse
import serial

DEFAULT_BAUDRATE = 9600

parser = argparse.ArgumentParser()

parser.add_argument("-p","--path", required=True, help="path to the sensor")
parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
parser.add_argument("-c", "--command", required=True, help="turn LED on / off")

args = parser.parse_args()

try:
    # open serial port
    ser = serial.Serial(args.path, baudrate=DEFAULT_BAUDRATE)
    ser.flushInput()

    if args.command:
        command=args.command
        ser.write(command+"\n")
finally:
    ser.close()
